import { Growth } from '@prisma/client';

const growths: Growth[] = [
  {
    id: 'G_1',
    nameEn: 'Section 1',
    nameVn: "Khu vực 1",
    cost: 0,
    order: 1,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_2',
    nameEn: 'Section 2',
    nameVn: "Khu vực 2",
    cost: 350,
    order: 2,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_3',
    nameEn: 'Section 3',
    nameVn: "Khu vực 3",
    cost: 750,
    order: 3,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_4',
    nameEn: 'Section 4',
    nameVn: "Khu vực 4",
    cost: 1300,
    order: 4,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_5',
    nameEn: 'Section 5',
    nameVn: "Khu vực 5",
    cost: 2600,
    order: 5,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_6',
    nameEn: 'Section 6',
    nameVn: "Khu vực 6",
    cost: 4400,
    order: 6,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_7',
    nameEn: 'Section 7',
    nameVn: "Khu vực 7",
    cost: 6700,
    order: 7,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_8',
    nameEn: 'Section 8',
    nameVn: "Khu vực 8",
    cost: 11000,
    order: 8,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_9',
    nameEn: 'Section 9',
    nameVn: "Khu vực 9",
    cost: 16500,
    order: 9,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_10',
    nameEn: 'Section 10',
    nameVn: "Khu vực 10",
    cost: 20100,
    order: 10,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_11',
    nameEn: 'Section 11',
    nameVn: "Khu vực 11",
    cost: 24600,
    order: 11,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_12',
    nameEn: 'Section 12',
    nameVn: "Khu vực 12",
    cost: 31000,
    order: 12,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_13',
    nameEn: 'Section 13',
    nameVn: "Khu vực 13",
    cost: 40000,
    order: 13,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_14',
    nameEn: 'Section 14',
    nameVn: "Khu vực 14",
    cost: 52000,
    order: 14,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_15',
    nameEn: 'Section 15',
    nameVn: "Khu vực 15",
    cost: 64500,
    order: 15,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_16',
    nameEn: 'Section 16',
    nameVn: "Khu vực 16",
    cost: 72600,
    order: 16,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_17',
    nameEn: 'Section 17',
    nameVn: "Khu vực 17",
    cost: 83500,
    order: 17,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_18',
    nameEn: 'Section 18',
    nameVn: "Khu vực 18",
    cost: 90000,
    order: 18,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_19',
    nameEn: 'Section 19',
    nameVn: "Khu vực 19",
    cost: 102000,
    order: 19,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_20',
    nameEn: 'Section 20',
    nameVn: "Khu vực 20",
    cost: 115000,
    order: 20,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_21',
    nameEn: 'Section 21',
    nameVn: "Khu vực 21",
    cost: 132000,
    order: 21,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_22',
    nameEn: 'Section 22',
    nameVn: "Khu vực 22",
    cost: 146000,
    order: 22,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_23',
    nameEn: 'Section 23',
    nameVn: "Khu vực 23",
    cost: 160000,
    order: 23,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default growths