import { Growth } from '@prisma/client';

const growths: Growth[] = [
  {
    id: 'G_1',
    name: 'Section 1 (Default)',
    cost: 0,
    order: 1,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_2',
    name: 'Section 2',
    cost: 350,
    order: 2,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_3',
    name: 'Section 3',
    cost: 750,
    order: 3,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_4',
    name: 'Section 4',
    cost: 1300,
    order: 4,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_5',
    name: 'Section 5',
    cost: 2600,
    order: 5,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_6',
    name: 'Section 6',
    cost: 4400,
    order: 6,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_7',
    name: 'Section 7',
    cost: 6700,
    order: 7,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_8',
    name: 'Section 8',
    cost: 11000,
    order: 8,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_9',
    name: 'Section 9',
    cost: 16500,
    order: 9,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_10',
    name: 'Section 10',
    cost: 20100,
    order: 10,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_11',
    name: 'Section 11',
    cost: 24600,
    order: 11,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_12',
    name: 'Section 12',
    cost: 31000,
    order: 12,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_13',
    name: 'Section 13',
    cost: 40000,
    order: 13,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_14',
    name: 'Section 14',
    cost: 52000,
    order: 14,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_15',
    name: 'Section 15',
    cost: 64500,
    order: 15,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_16',
    name: 'Section 16',
    cost: 72600,
    order: 16,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_17',
    name: 'Section 17',
    cost: 83500,
    order: 17,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_18',
    name: 'Section 18',
    cost: 90000,
    order: 18,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_19',
    name: 'Section 19',
    cost: 102000,
    order: 19,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_20',
    name: 'Section 20',
    cost: 115000,
    order: 20,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_21',
    name: 'Section 21',
    cost: 132000,
    order: 21,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_22',
    name: 'Section 22',
    cost: 146000,
    order: 22,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'G_23',
    name: 'Section 23',
    cost: 160000,
    order: 23,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default growths