import { Loan } from '@prisma/client';
import { ELoanType } from 'src/modules/loan/loan.enum';

const loans: Loan[] = [
  {
    id: 'L_1',
    type: ELoanType.BASIC,
    cost: 750,
    payment: 57.5,
    termLength: 15,
    totalReturn: 862.5,
    interest: 1,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'L_2',
    type: ELoanType.MEDIUM,
    cost: 2000,
    payment: 173,
    termLength: 15,
    totalReturn: 2.600,
    interest: 2,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'L_3',
    type: ELoanType.PROFESSIONAL,
    cost: 5000,
    payment: 483,
    termLength: 15,
    totalReturn: 7250,
    interest: 3,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'L_4',
    type: ELoanType.CORPORATE,
    cost: 15000,
    payment: 1600,
    termLength: 15,
    totalReturn: 24000,
    interest: 4,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'L_5',
    type: ELoanType.PREMIUM,
    cost: 50000,
    payment: 5583,
    termLength: 15,
    totalReturn: 83750,
    interest: 4.5,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'L_6',
    type: ELoanType.MEGA,
    cost: 100000,
    payment: 11.667,
    termLength: 15,
    totalReturn: 175000,
    interest: 5,
    isDelete: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default loans;
