import { Product } from '@prisma/client';
import { EProductDisplay, EProductUnit, EStorageStatus } from '../../src/modules/product/product.enum';
import { ERecordStatus } from '../../src/common/enum/base';

const items = [
  {
    nameEn: 'Apple Juice',
    nameVn: 'Nước ép táo',
    company: 'Bio Juice',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 6.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Beer Blonde Ale',
    nameVn: 'Bia Blonde Ale (Chai lẻ)',
    company: 'Fess',
    display: EProductDisplay.FRIDGE,
    items: 15,
    unit: EProductUnit.BOTTLE,
    price: 4.5,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Blonde Ale',
    nameVn: 'Bia Blonde Ale (Chai lẻ)',
    company: 'BK',
    display: EProductDisplay.FRIDGE,
    items: 15,
    unit: EProductUnit.BOTTLE,
    price: 4.5,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Blonde Ale 6-Pack',
    nameVn: 'Lốc 6 chai Bia Blonde Ale',
    company: 'Fess',
    display: EProductDisplay.SHELF,
    items: 9,
    unit: EProductUnit.PACK,
    price: 22.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Blonde Ale 6-Pack',
    nameVn: 'Lốc 6 chai Bia Blonde Ale',
    company: 'BK',
    display: EProductDisplay.SHELF,
    items: 9,
    unit: EProductUnit.PACK,
    price: 22.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Blonde Ale Keg',
    nameVn: 'Bom bia Blonde Ale',
    company: 'Fess',
    display: EProductDisplay.SHELF,
    items: 6,
    unit: EProductUnit.KEG,
    price: 45.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Blonde Ale Keg',
    nameVn: 'Bom bia Blonde Ale',
    company: 'Degl',
    display: EProductDisplay.SHELF,
    items: 6,
    unit: EProductUnit.KEG,
    price: 45.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Lager',
    nameVn: 'Bia Lager (Chai lẻ)',
    company: 'Teochew',
    display: EProductDisplay.FRIDGE,
    items: 15,
    unit: EProductUnit.BOTTLE,
    price: 5.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Lager 6-Pack',
    nameVn: 'Lốc 6 chai Bia Lager',
    company: 'Teochew',
    display: EProductDisplay.SHELF,
    items: 9,
    unit: EProductUnit.PACK,
    price: 24.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Beer Lager Keg',
    nameVn: 'Bom bia Lager',
    company: 'Teochew',
    display: EProductDisplay.SHELF,
    items: 6,
    unit: EProductUnit.KEG,
    price: 48.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Bleach',
    nameVn: 'Thuốc tẩy quần áo',
    company: 'Jaja Vevel',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BOTTLE,
    price: 7.5,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Bleach',
    nameVn: 'Thuốc tẩy bồn cầu',
    company: 'WC Boeff',
    display: EProductDisplay.SHELF,
    items: 6,
    unit: EProductUnit.BOTTLE,
    price: 8.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Abc',
    company: 'Abc',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Colors',
    company: 'Colors',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Donnine',
    company: 'Donnine',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Electromagnetic Field',
    company: 'Electromagnetic Field',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 18.0,
    categoryId: 'C_12',
  },
  {
    nameEn: "I Won't Share",
    nameVn: "Sách I Won't Share",
    company: "I Won't Share",
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Mother And Child',
    company: 'Mother And Child',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Krok',
    company: 'Krok',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Once Upon A Time',
    company: 'Once Upon A Time',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Piticha',
    company: 'Piticha',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách The Surprise',
    company: 'The Surprise',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Vintage Story',
    company: 'Vintage Story',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Book',
    nameVn: 'Sách Wombat',
    company: 'Wombat',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PIECE,
    price: 15.0,
    categoryId: 'C_12',
  },
  {
    nameEn: 'Bottled Water',
    nameVn: 'Nước khoáng đóng chai',
    company: 'Aotte',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 2.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Bottled Water',
    nameVn: 'Nước khoáng đóng chai',
    company: 'Montcuq',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 2.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Bottled Water',
    nameVn: 'Nước khoáng đóng chai cao cấp',
    company: 'Fort-Lacs',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 3.0,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Butter',
    nameVn: 'Bơ lạt',
    company: 'Paysans',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.PACK,
    price: 5.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh ngọt Bon Papa',
    company: 'Bon Papa',
    display: EProductDisplay.SHELF,
    items: 15,
    unit: EProductUnit.BOX,
    price: 9.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh ngọt Pépites',
    company: 'Pépites',
    display: EProductDisplay.SHELF,
    items: 18,
    unit: EProductUnit.BOX,
    price: 8.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh ngọt Gerbe',
    company: 'Gerbe',
    display: EProductDisplay.SHELF,
    items: 15,
    unit: EProductUnit.BOX,
    price: 9.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh cuộn Marbré',
    company: 'Marbré',
    display: EProductDisplay.SHELF,
    items: 18,
    unit: EProductUnit.BOX,
    price: 8.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh bông lan Prairie',
    company: 'Prairie',
    display: EProductDisplay.SHELF,
    items: 18,
    unit: EProductUnit.BOX,
    price: 8.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cake',
    nameVn: 'Bánh ngọt St Michmich',
    company: 'St Michmich',
    display: EProductDisplay.SHELF,
    items: 15,
    unit: EProductUnit.BOX,
    price: 9.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Candy',
    nameVn: 'Kẹo dẻo / Kẹo mút',
    company: 'Bonbek',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.PACK,
    price: 4.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cat Food',
    nameVn: 'Thức ăn cho mèo (Dạng lon)',
    company: 'Miaoumiam',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.CAN,
    price: 6.0,
    categoryId: 'C_13',
  },
  {
    nameEn: 'Cat Food',
    nameVn: 'Thức ăn cho mèo cao cấp',
    company: 'Patpat',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.CAN,
    price: 6.0,
    categoryId: 'C_13',
  },
  {
    nameEn: 'Cereal',
    nameVn: 'Ngũ cốc Chokipik',
    company: 'Chokipik',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 6.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cereal',
    nameVn: 'Ngũ cốc Crispy Chibi',
    company: 'Crispy Chibi',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 7.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cereal',
    nameVn: 'Ngũ cốc vị mật ong Honey Bees',
    company: 'Honey Bees',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 6.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Cheese',
    nameVn: 'Phô mai Comté',
    company: 'Comté',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 11.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cheese',
    nameVn: 'Phô mai Mimolette',
    company: 'Mimolette',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 10.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cheese Gruyere',
    nameVn: 'Phô mai bào Gruyere',
    company: 'Eros',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 12.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cheese Mozarella',
    nameVn: 'Phô mai Mozzarella',
    company: 'Don Bernardo',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 9.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cheese Parmesan',
    nameVn: 'Phô mai Parmesan khối',
    company: 'Don Bernardo',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 13.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Cheese Parmesan',
    nameVn: 'Phô mai Parmesan khối Eros',
    company: 'Eros',
    display: EProductDisplay.FRIDGE,
    items: 9,
    unit: EProductUnit.PACK,
    price: 13.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Chicken',
    nameVn: 'Thịt gà nguyên con',
    company: 'Mwef',
    display: EProductDisplay.FREEZER,
    items: 4,
    unit: EProductUnit.PACK,
    price: 18.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Chicken Leg',
    nameVn: 'Đùi gà tươi',
    company: 'Bovora',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.PACK,
    price: 14.0,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Chips',
    nameVn: 'Khoai tây chiên Covidos',
    company: 'Covidos',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.BAG,
    price: 4.5,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Chips',
    nameVn: 'Khoai tây chiên Chipos',
    company: 'Chipos',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.BAG,
    price: 4.5,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Chips',
    nameVn: "Khoai tây chiên Vin's",
    company: "Vin's",
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.BAG,
    price: 5.0,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Chocolate Bar',
    nameVn: 'Thanh sô-cô-la Chocotte',
    company: 'Chocotte',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BAR,
    price: 3.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Chocolate Bar',
    nameVn: 'Thanh sô-cô-la Denorme',
    company: 'Denorme',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BAR,
    price: 3.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Chocolate Powder',
    nameVn: 'Bột sô-cô-la / Ca-cao',
    company: 'Boudain',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BOX,
    price: 8.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Chocolate Spread',
    nameVn: 'Mứt sô-cô-la phết bánh mì',
    company: 'Patatartine',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.JAR,
    price: 6.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Cleaner',
    nameVn: 'Nước lau đa năng',
    company: 'Touprop',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 9.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Cleaner',
    nameVn: 'Nước lau đa năng',
    company: 'Kilemol',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 9.5,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Cleaner',
    nameVn: 'Nước lau kính',
    company: 'Yamo',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 9.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Cleaner',
    nameVn: 'Xịt tẩy rửa mạnh',
    company: 'Wesh',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 10.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Cleaner',
    nameVn: 'Nước lau sàn',
    company: 'Le Triangle',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 9.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Coffee Dark Roast',
    nameVn: 'Cà phê rang đậm',
    company: 'Narvalo',
    display: EProductDisplay.SHELF,
    items: 7,
    unit: EProductUnit.PACK,
    price: 12.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Coffee Light Roast',
    nameVn: 'Cà phê rang nhạt',
    company: 'Narvalo',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 11.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Coffee Medium Roast',
    nameVn: 'Cà phê rang vừa',
    company: 'Narvalo',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 12.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Crab Stick',
    nameVn: 'Thanh cua đông lạnh',
    company: 'Sans',
    display: EProductDisplay.FREEZER,
    items: 24,
    unit: EProductUnit.PACK,
    price: 7.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Crème Fraîche Epaisse',
    nameVn: 'Kem tươi đặc (Crème Fraîche)',
    company: 'Etron',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.JAR,
    price: 5.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Dish Soap Durian',
    nameVn: 'Nước rửa chén hương sầu riêng',
    company: 'Sapu',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 5.5,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Dish Soap Lemon',
    nameVn: 'Nước rửa chén hương chanh',
    company: 'Mouss',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 5.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Dishwasher Tablet',
    nameVn: 'Viên rửa chén Cleandish',
    company: 'Cleandish',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 14.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Dishwasher Tablet',
    nameVn: 'Viên rửa chén Boum',
    company: 'Boum',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 14.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Dishwasher Tablet',
    nameVn: 'Viên rửa chén cao cấp',
    company: 'Cemagik',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BOX,
    price: 16.5,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Dog Food',
    nameVn: 'Thức ăn cho chó (Dạng lon)',
    company: 'Patpat',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.CAN,
    price: 8.5,
    categoryId: 'C_13',
  },
  {
    nameEn: 'Eggs 12-Pack',
    nameVn: 'Vỉ trứng 12 quả',
    company: 'Bio',
    display: EProductDisplay.FRIDGE,
    items: 12,
    unit: EProductUnit.PACK,
    price: 7.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Eggs 4-Pack',
    nameVn: 'Hộp trứng 4 quả',
    company: 'Bio',
    display: EProductDisplay.FRIDGE,
    items: 12,
    unit: EProductUnit.PACK,
    price: 3.2,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Eggs 8-Pack',
    nameVn: 'Hộp trứng 8 quả',
    company: 'Bio',
    display: EProductDisplay.FRIDGE,
    items: 12,
    unit: EProductUnit.PACK,
    price: 5.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Fabric Softener',
    nameVn: 'Nước xả vải Souplesse',
    company: 'Souplesse',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 11.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Fabric Softener',
    nameVn: 'Nước xả vải Toudou',
    company: 'Toudou',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 11.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Flour',
    nameVn: 'Bột mì Kraftung',
    company: 'Kraftung',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BAG,
    price: 4.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Flour',
    nameVn: 'Bột mì Farine',
    company: 'Farine',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BAG,
    price: 4.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Flour',
    nameVn: "Bột mì Sublett's",
    company: "Sublett's",
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.BAG,
    price: 4.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'French Fries',
    nameVn: 'Khoai tây chiên đóng bao (Đông lạnh)',
    company: "Vandame's",
    display: EProductDisplay.FREEZER,
    items: 12,
    unit: EProductUnit.BAG,
    price: 6.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Galette Ham&Cheese',
    nameVn: 'Bánh Galette nhân thịt nguội & phô mai',
    company: 'Prypiat',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOX,
    price: 9.5,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Green Beans',
    nameVn: 'Đậu xanh đông lạnh',
    company: 'MrBean',
    display: EProductDisplay.FREEZER,
    items: 12,
    unit: EProductUnit.BAG,
    price: 5.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Ground Beef',
    nameVn: 'Thịt bò xay',
    company: 'Bovora',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.PACK,
    price: 15.5,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Ham',
    nameVn: 'Thịt nguội cắt lát',
    company: 'B&K',
    display: EProductDisplay.FRIDGE,
    items: 20,
    unit: EProductUnit.PACK,
    price: 10.0,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Ham Pastry',
    nameVn: 'Bánh nướng nhân thịt nguội',
    company: 'Ronpoint',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOX,
    price: 9.0,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Hand Soap',
    nameVn: 'Nước rửa tay',
    company: 'Savion',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 4.5,
    categoryId: 'C_10',
  },
  {
    nameEn: 'Honey',
    nameVn: 'Mật ong nguyên chất',
    company: 'Hone',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.JAR,
    price: 9.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Hot Sauce',
    nameVn: 'Tương ớt siêu cay',
    company: 'Hothot',
    display: EProductDisplay.SHELF,
    items: 1,
    unit: EProductUnit.BOTTLE,
    price: 6.0,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Houmus',
    nameVn: 'Sốt Houmus (Đậu răng ngựa)',
    company: 'Bibi',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.TUB,
    price: 5.5,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Ice cream',
    nameVn: 'Kem hộp lớn',
    company: 'Bonbek',
    display: EProductDisplay.FREEZER,
    items: 24,
    unit: EProductUnit.TUB,
    price: 10.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Ice cream Chocolate',
    nameVn: 'Kem cây vị Sô-cô-la (Hộp)',
    company: 'MaxiCone',
    display: EProductDisplay.FREEZER,
    items: 24,
    unit: EProductUnit.BOX,
    price: 12.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Ice cream Vanille',
    nameVn: 'Kem cây vị Vani (Hộp)',
    company: 'MaxiCone',
    display: EProductDisplay.FREEZER,
    items: 24,
    unit: EProductUnit.BOX,
    price: 12.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Ketchup',
    nameVn: 'Tương cà',
    company: 'Kekette',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 4.8,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Lasagne',
    nameVn: 'Mì Ý nướng Lasagne (Ăn liền)',
    company: 'Ronpoint',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOX,
    price: 12.5,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Mashed Potatoes',
    nameVn: 'Khoai tây nghiền ăn liền',
    company: 'Puray',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 5.5,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Mayonnaise',
    nameVn: 'Sốt Mayonnaise',
    company: 'Yoyo',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.JAR,
    price: 5.0,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Milk',
    nameVn: 'Sữa tươi (Chai)',
    company: 'Bourlait',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 3.5,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Milk 6-Pack',
    nameVn: 'Thùng lốc 6 hộp sữa giấy',
    company: 'Labol',
    display: EProductDisplay.SHELF,
    items: 6,
    unit: EProductUnit.PACK,
    price: 18.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Moussaka',
    nameVn: 'Món bỏ lò Moussaka (Ăn liền)',
    company: 'Ronpoint',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOX,
    price: 13.0,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Oil',
    nameVn: 'Dầu ăn thực vật',
    company: 'Lespieds',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 7.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Olive Oil',
    nameVn: 'Dầu Ô-liu',
    company: 'Tupiges',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 11.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Orange Juice',
    nameVn: 'Nước ép cam',
    company: 'Bio Juice',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOTTLE,
    price: 6.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Paper Towel',
    nameVn: 'Giấy lau bếp / Băng cuộn',
    company: 'Compact',
    display: EProductDisplay.SHELF,
    items: 4,
    unit: EProductUnit.PACK,
    price: 6.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Pasta',
    nameVn: 'Nui ống Panzati',
    company: 'Panzati',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 3.2,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Pasta Elbows',
    nameVn: 'Nui cong Lustupacru',
    company: 'Lustupacru',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 3.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Pasta Penne',
    nameVn: 'Mì ống Penne Parillo',
    company: 'Parillo',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 3.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Pasta Spaghetti',
    nameVn: 'Mì sợi dài Spaghetti',
    company: 'Elo',
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.PACK,
    price: 3.2,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Peanut Butter',
    nameVn: 'Bơ đậu phộng',
    company: "PB's",
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.JAR,
    price: 6.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Pepper',
    nameVn: 'Tiêu xay (Hũ rắc)',
    company: 'Afyon',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.SHAKER,
    price: 4.8,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Pizza',
    nameVn: 'Bánh Pizza truyền thống (Đông lạnh)',
    company: 'Bigtony',
    display: EProductDisplay.FREEZER,
    items: 32,
    unit: EProductUnit.BOX,
    price: 8.5,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Pizza Cheddar',
    nameVn: 'Bánh Pizza phô mai Cheddar',
    company: 'CheezyPizz',
    display: EProductDisplay.FREEZER,
    items: 32,
    unit: EProductUnit.BOX,
    price: 9.0,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Pizza Mixed',
    nameVn: 'Bánh Pizza thập cẩm đặc biệt',
    company: 'DeNiro',
    display: EProductDisplay.FREEZER,
    items: 32,
    unit: EProductUnit.BOX,
    price: 9.5,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Potato Bag',
    nameVn: 'Bao khoai tây tươi',
    company: 'Miam',
    display: EProductDisplay.SHELF,
    items: 4,
    unit: EProductUnit.BAG,
    price: 10.5,
    categoryId: 'C_3',
  },
  {
    nameEn: 'Potato Pops',
    nameVn: 'Bánh khoai tây viên (Đông lạnh)',
    company: 'Spok',
    display: EProductDisplay.FREEZER,
    items: 12,
    unit: EProductUnit.BAG,
    price: 6.5,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Proscuito',
    nameVn: 'Thịt heo muối Tây Ban Nha',
    company: 'Sapore',
    display: EProductDisplay.FRIDGE,
    items: 20,
    unit: EProductUnit.PACK,
    price: 11.5,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Rice',
    nameVn: 'Gạo',
    company: 'Elo',
    display: EProductDisplay.SHELF,
    items: 10,
    unit: EProductUnit.BAG,
    price: 5.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Rice Basmati',
    nameVn: 'Gạo hạt dài Basmati',
    company: 'Lustupacru',
    display: EProductDisplay.SHELF,
    items: 10,
    unit: EProductUnit.BAG,
    price: 6.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Rice Long Grain',
    nameVn: 'Gạo lứt hạt dài',
    company: "Uncle Tony's",
    display: EProductDisplay.SHELF,
    items: 10,
    unit: EProductUnit.BAG,
    price: 5.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Salmon',
    nameVn: 'Filet cá hồi tươi',
    company: 'Nordic Harbor',
    display: EProductDisplay.FRIDGE,
    items: 20,
    unit: EProductUnit.PACK,
    price: 16.0,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Salt',
    nameVn: 'Muối ăn (Hũ rắc)',
    company: 'Labalaine',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.SHAKER,
    price: 3.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sandwich Bread',
    nameVn: 'Bánh mì gối / Sandwich',
    company: "Ron's",
    display: EProductDisplay.SHELF,
    items: 8,
    unit: EProductUnit.LOAF,
    price: 4.0,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Scallop Gratin',
    nameVn: 'Sò điệp đút lò phô mai (Ăn liền)',
    company: 'Prypiat',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOX,
    price: 11.0,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Shampoo',
    nameVn: 'Dầu gội đầu',
    company: 'Kaya',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 8.5,
    categoryId: 'C_10',
  },
  {
    nameEn: 'Sliced Bread',
    nameVn: 'Bánh mì lát gối lớn',
    company: "Ron's",
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.LOAF,
    price: 4.5,
    categoryId: 'C_2',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt vị Cola (Chai)',
    company: 'Cola',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.2,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt vị tăng lực Zap (Chai)',
    company: 'Zap',
    display: EProductDisplay.FRIDGE,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 3.2,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt vị Turko (Chai)',
    company: 'Turko',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.2,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt hương trái cây Jus Tsistu',
    company: 'Jus Tsistu',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt vị Koujeima (Chai)',
    company: 'Koujeima',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.2,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt có ga vị cam Pulp',
    company: 'Pulp',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda',
    nameVn: 'Nước ngọt trái cây Ropico',
    company: 'Ropico',
    display: EProductDisplay.FRIDGE,
    items: 24,
    unit: EProductUnit.BOTTLE,
    price: 3.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda Can 6-Pack',
    nameVn: 'Lốc 6 lon nước ngọt Cola',
    company: 'Cola',
    display: EProductDisplay.SHELF,
    items: 24,
    unit: EProductUnit.PACK,
    price: 14.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Soda Can 6-Pack',
    nameVn: 'Lốc 6 lon nước ngọt Zap',
    company: 'Zap',
    display: EProductDisplay.SHELF,
    items: 24,
    unit: EProductUnit.PACK,
    price: 14.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Steak',
    nameVn: 'Thịt bò bít tết tươi',
    company: 'Bovora',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.PACK,
    price: 17.0,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Sugar',
    nameVn: 'Đường trắng tinh luyện',
    company: 'Daron',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.PACK,
    price: 4.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Brown',
    nameVn: 'Đường nâu',
    company: 'Susu',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.PACK,
    price: 4.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Cane',
    nameVn: 'Đường mía tự nhiên',
    company: 'Daron',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.PACK,
    price: 4.8,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Light Brown',
    nameVn: 'Đường nâu nhạt',
    company: 'Daron',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.PACK,
    price: 4.5,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Powdered',
    nameVn: 'Đường bột làm bánh Susu',
    company: 'Susu',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 5.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Powdered',
    nameVn: 'Đường bột làm bánh Pablo',
    company: 'Pablo',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 5.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sugar Powdered',
    nameVn: 'Đường bột làm bánh Boully',
    company: 'Boully',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOX,
    price: 5.0,
    categoryId: 'C_1',
  },
  {
    nameEn: 'Sushi Large',
    nameVn: 'Hộp Sushi lớn (Ăn liền)',
    company: 'Ulego',
    display: EProductDisplay.FRIDGE,
    items: 8,
    unit: EProductUnit.BOX,
    price: 19.0,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Sushi Small',
    nameVn: 'Hộp Sushi nhỏ (Ăn liền)',
    company: 'Ulego',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.BOX,
    price: 11.0,
    categoryId: 'C_8',
  },
  {
    nameEn: 'Tea Black',
    nameVn: 'Trà đen đóng hộp',
    company: 'Tea Palace',
    display: EProductDisplay.SHELF,
    items: 20,
    unit: EProductUnit.BOX,
    price: 6.5,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Tea Green',
    nameVn: 'Trà xanh đóng hộp',
    company: 'Tea Palace',
    display: EProductDisplay.SHELF,
    items: 48,
    unit: EProductUnit.BOX,
    price: 7.0,
    categoryId: 'C_4',
  },
  {
    nameEn: 'Toilet Paper',
    nameVn: 'Giấy vệ sinh Poudou',
    company: 'Poudou',
    display: EProductDisplay.SHELF,
    items: 4,
    unit: EProductUnit.PACK,
    price: 8.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Toilet Paper',
    nameVn: 'Giấy vệ sinh Bidet',
    company: 'Bidet',
    display: EProductDisplay.SHELF,
    items: 4,
    unit: EProductUnit.PACK,
    price: 8.0,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Toilet Paper',
    nameVn: 'Giấy vệ sinh cao cấp Petus',
    company: 'Petus',
    display: EProductDisplay.SHELF,
    items: 4,
    unit: EProductUnit.PACK,
    price: 8.5,
    categoryId: 'C_9',
  },
  {
    nameEn: 'Toothpaste',
    nameVn: 'Kem đánh răng',
    company: 'Signoulos',
    display: EProductDisplay.SHELF,
    items: 16,
    unit: EProductUnit.TUBE,
    price: 4.5,
    categoryId: 'C_10',
  },
  {
    nameEn: 'Tuna',
    nameVn: 'Cá ngừ đóng lon',
    company: 'Stark',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.CAN,
    price: 6.5,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Veal Chop',
    nameVn: 'Sườn bê tươi',
    company: 'Bovora',
    display: EProductDisplay.FRIDGE,
    items: 16,
    unit: EProductUnit.PACK,
    price: 18.5,
    categoryId: 'C_7',
  },
  {
    nameEn: 'Veggie Mix',
    nameVn: 'Rau củ hỗn hợp (Đông lạnh)',
    company: 'Ege',
    display: EProductDisplay.FREEZER,
    items: 12,
    unit: EProductUnit.BAG,
    price: 5.5,
    categoryId: 'C_6',
  },
  {
    nameEn: 'Vodka',
    nameVn: 'Rượu Vodka Eay',
    company: 'Eay',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 32.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Vodka',
    nameVn: 'Rượu Vodka thượng hạng Magnat',
    company: 'Magnat',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 35.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Whiskey',
    nameVn: 'Rượu Whiskey Grand Marnier',
    company: 'Grand Marnier',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 45.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Whiskey',
    nameVn: 'Rượu Whiskey Jack Sublett',
    company: 'Jack Sublett',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 50.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Whiskey',
    nameVn: 'Rượu Whiskey Nhật Bản',
    company: 'Japanese',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 55.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Wine',
    nameVn: 'Rượu vang đỏ Chebon',
    company: 'Chebon',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 24.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Wine',
    nameVn: 'Rượu vang Heng',
    company: 'Heng',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 26.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Wine',
    nameVn: 'Rượu vang cổ Pouilleux',
    company: 'Pouilleux',
    display: EProductDisplay.SHELF,
    items: 12,
    unit: EProductUnit.BOTTLE,
    price: 22.0,
    categoryId: 'C_11',
  },
  {
    nameEn: 'Yoghurt',
    nameVn: 'Sữa chua Trái cây Frügen',
    company: 'Frügen',
    display: EProductDisplay.FRIDGE,
    items: 30,
    unit: EProductUnit.PACK,
    price: 4.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Yoghurt',
    nameVn: 'Sữa chua Madone',
    company: 'Madone',
    display: EProductDisplay.FRIDGE,
    items: 30,
    unit: EProductUnit.PACK,
    price: 4.0,
    categoryId: 'C_5',
  },
  {
    nameEn: 'Yoghurt',
    nameVn: 'Sữa chua uống Yowp',
    company: 'Yowp',
    display: EProductDisplay.FRIDGE,
    items: 30,
    unit: EProductUnit.PACK,
    price: 4.5,
    categoryId: 'C_5',
  },
];

const products: Product[] = [...items].map(
  ({ nameEn, nameVn, company, display, unit, price, items, categoryId }, idx) => ({
    id: `P_${idx + 1}`,
    nameEn,
    nameVn,
    unit,
    display,
    cost: price,
    price: price + 0.3,
    items,
    categoryId,
    boxes: 10,
    amount: items * 10,
    status: ERecordStatus.ACTIVE,
    storageStatus: EStorageStatus.IN_STOCK,
    supplier: company,
    isNew: false,
    isDelete: false,
    updatedAt: new Date(),
    createdAt: new Date(),
}),
);

export default products;
