import { User } from '@prisma/client';
import { EGender, ERole } from '../../src/modules/user/user.enum';
import utils from '../../src/utils';

const users: User[] = [
  {
    id: 'US_1',
    email: 'nhambontuong68@gmail.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Tuong',
    lastName: 'Anderson',
    fullName: 'Jack Anderson',
    phone: '0793229970',
    gender: EGender.MALE,
    birthday: '1994-11-28T00:00:00.000Z',
    role: ERole.OWNER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_2',
    email: 'claire@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Claire',
    lastName: 'Redfield',
    fullName: 'Claire Redfield',
    phone: '0593114491',
    gender: EGender.FEMALE,
    birthday: '1997-11-28T00:00:00.000Z',
    role: ERole.MANAGER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_3',
    email: 'kevin@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Kevin',
    lastName: 'Kowalski',
    fullName: 'Kevin Kowalski',
    phone: '0793886681',
    gender: EGender.MALE,
    birthday: '1984-01-15T00:00:00.000Z',
    role: ERole.MANAGER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_4',
    email: 'bill@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Bill',
    lastName: 'Batson',
    fullName: 'Bill Batson',
    phone: '0854266700',
    gender: EGender.MALE,
    birthday: '1994-01-15T00:00:00.000Z',
    role: ERole.LEADER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_5',
    email: 'emily@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Emily',
    lastName: 'Castle',
    fullName: 'Emily Castle',
    phone: '0793886671',
    gender: EGender.FEMALE,
    birthday: '1997-02-28T00:00:00.000Z',
    role: ERole.LEADER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_6',
    email: 'anna@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Anna',
    lastName: 'Pennyworth',
    fullName: 'Anna Pennyworth',
    phone: '0593886651',
    gender: EGender.FEMALE,
    birthday: '2000-11-15T00:00:00.000Z',
    role: ERole.STOCKER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_7',
    email: 'John@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'John',
    lastName: 'Drake',
    fullName: 'John Drake',
    phone: '0793886651',
    gender: EGender.MALE,
    birthday: '1999-09-28T00:00:00.000Z',
    role: ERole.STOCKER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_8',
    email: 'ben@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Ben',
    lastName: 'Anderson',
    fullName: 'Ben Anderson',
    phone: '0793664475',
    gender: EGender.MALE,
    birthday: '1993-01-15T00:00:00.000Z',
    role: ERole.STOCKER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_9',
    email: 'eva@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Eva',
    lastName: 'Queen',
    fullName: 'Eva Queen',
    phone: '0793886687',
    gender: EGender.FEMALE,
    birthday: '1990-11-15T00:00:00.000Z',
    role: ERole.STOCKER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_10',
    email: 'evan@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Evan',
    lastName: 'Todd',
    fullName: 'Evan Todd',
    phone: '0293885541',
    gender: EGender.MALE,
    birthday: '1995-03-10T00:00:00.000Z',
    role: ERole.CASHIER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_11',
    email: 'lily@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Lily',
    lastName: 'Simmons',
    fullName: 'Lily Simmons',
    phone: '0293885531',
    gender: EGender.FEMALE,
    birthday: '1995-03-11T00:00:00.000Z',
    role: ERole.CASHIER,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_12',
    email: 'lily@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Lily',
    lastName: 'Williams',
    fullName: 'Lily Williams',
    phone: '0293885521',
    gender: EGender.FEMALE,
    birthday: '2000-03-11T00:00:00.000Z',
    role: ERole.CUSTOMER_SERVICE,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_13',
    email: 'margaret@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Margaret',
    lastName: 'Wayne',
    fullName: 'Margaret Wayne',
    phone: '0293886631',
    gender: EGender.FEMALE,
    birthday: '2001-05-11T00:00:00.000Z',
    role: ERole.CUSTOMER_SERVICE,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_14',
    email: 'jack@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Jack',
    lastName: 'Butcher',
    fullName: 'Jack Butcher',
    phone: '0293886630',
    gender: EGender.MALE,
    birthday: '1998-05-11T00:00:00.000Z',
    role: ERole.JANITOR,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_15',
    email: 'scott@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Scott',
    lastName: 'Jefferson',
    fullName: 'Scott Jefferson',
    phone: '0293876620',
    gender: EGender.MALE,
    birthday: '2001-05-11T00:00:00.000Z',
    role: ERole.JANITOR,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_16',
    email: 'peter@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Peter',
    lastName: 'Jefferson',
    fullName: 'Peter Jefferson',
    phone: '0293576630',
    gender: EGender.MALE,
    birthday: '1994-05-11T00:00:00.000Z',
    role: ERole.SECURITY,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'US_17',
    email: 'howard@example.com',
    password: utils.bcryptHash('123456'),
    firstName: 'Howard',
    lastName: 'Potts',
    fullName: 'Howard Potts',
    phone: '0293876610',
    gender: EGender.MALE,
    birthday: '1995-05-11T00:00:00.000Z',
    role: ERole.SECURITY,
    isDelete: false,
    resetToken: null,
    resetTokenExpires: null,
    googleId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default users;
